swagger: "2.0"
info:
  description: "Documentação da API do projeto de Nota Fiscal"
  version: "1.0.0"
  title: "Nota Fiscal API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "karinelucion04@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "quarkusnotafiscal.github.io"
basePath: "/"
tags:
  - name: "endereco"
    description: "Operações do endereço"
  - name: "fornecedor"
    description: "Operações do fornecedor"
  - name: "nota fiscal"
    description: "Operações da nota fiscal"
  - name: "produto"
    description: "Operações do produto"

paths:
  /endereco:
    get:
      tags:
        - "endereco"
      summary: "Lista todos os endereços"
      responses:
        "200":
          description: "OK"

  /fornecedor:
    get:
      tags:
        - "fornecedor"
      summary: "Lista todos os fornecedores"
      responses:
        "200":
          description: "OK"
    post:
      tags:
        - "fornecedor"
      summary: "Cria um novo fornecedor"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "Fornecedor"
          required: true
          schema:
            $ref: "#/definitions/Fornecedor"
      responses:
        "200":
          description: "Fornecedor criado com sucesso"

  /fornecedor/{id}:
    put:
      tags:
        - "fornecedor"
      summary: "Atualiza um fornecedor pelo ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
        - in: "body"
          name: "Fornecedor"
          required: true
          schema:
            $ref: "#/definitions/Fornecedor"
      responses:
        "200":
          description: "Fornecedor atualizado com sucesso"
    delete:
      tags:
        - "fornecedor"
      summary: "Deleta um fornecedor pelo ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
      responses:
        "200":
          description: "Fornecedor deletado com sucesso"

  /notafiscal:
    get:
      tags:
        - "nota fiscal"
      summary: "Lista todas as notas fiscais"
      responses:
        "200":
          description: "OK"
    post:
      tags:
        - "nota fiscal"
      summary: "Cria uma nova nota fiscal"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "NotaFiscal"
          required: true
          schema:
            $ref: "#/definitions/NotaFiscal"
      responses:
        "200":
          description: "Nota fiscal criada com sucesso"

  /notafiscal/{id}:
    put:
      tags:
        - "nota fiscal"
      summary: "Atualiza uma nota fiscal pelo ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
        - in: "body"
          name: "NotaFiscal"
          required: true
          schema:
            $ref: "#/definitions/NotaFiscal"
      responses:
        "200":
          description: "Nota fiscal atualizada com sucesso"
    delete:
      tags:
        - "nota fiscal"
      summary: "Deleta uma nota fiscal pelo ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
      responses:
        "200":
          description: "Nota fiscal deletada com sucesso"

  /produto:
    get:
      tags:
        - "produto"
      summary: "Lista todos os produtos"
      responses:
        "200":
          description: "OK"
    post:
      tags:
        - "produto"
      summary: "Cria um novo produto"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "Produto"
          required: true
          schema:
            $ref: "#/definitions/Produto"
      responses:
        "200":
          description: "Produto criado com sucesso"

  /produto/{id}:
    put:
      tags:
        - "produto"
      summary: "Atualiza um produto pelo ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
        - in: "body"
          name: "Produto"
          required: true
          schema:
            $ref: "#/definitions/Produto"
      responses:
        "200":
          description: "Produto atualizado com sucesso"
    delete:
      tags:
        - "produto"
      summary: "Deleta um produto pelo ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
      responses:
        "200":
          description: "Produto deletado com sucesso"

definitions:
  Endereco:
    type: "object"
    properties:
      id:
        type: "integer"
      cep:
        type: "string"
      logradouro:
        type: "string"
      complemento:
        type: "string"
      bairro:
        type: "string"
      localidade:
        type: "string"
      uf:
        type: "string"
      numero:
        type: "string"

  Fornecedor:
    type: "object"
    properties:
      id:
        type: "integer"
      razaosocial:
        type: "string"
      email:
        type: "string"
      telefone:
        type: "string"
      cnpj:
        type: "string"
      situacao:
        type: "string"
      databaixa:
        type: "string"
        format: "date"

  NotaFiscal:
    type: "object"
    properties:
      id:
        type: "integer"
      numero:
        type: "string"
      datahora:
        type: "string"
        format: "date-time"
      valortotal:
        type: "number"
      endereco:
        $ref: "#/definitions/Endereco"
      fornecedor:
        $ref: "#/definitions/Fornecedor"
      itens:
        type: "array"
        items:
          $ref: "#/definitions/Produto"

  Produto:
    type: "object"
    properties:
      id:
        type: "integer"
      descricao:
        type: "string"
      preco:
        type: "number"
      situacao:
        type: "string"